# Assignment 6

### Complete all questions below in the fields provided. For this assignment, we will use `numpy`, imported here.

In [1]:
import numpy as np

## Section 1 -- Basic array operations

#### 1. Using the appropriate functions for lists, make a list `L` of all integers from 0 - 19 (inclusive). 

In [2]:
L = list(range(20))

#### 2. Use a numpy function to convert `L` into a numpy array.

In [3]:
L = np.array(L)

#### 3. Redo \#1 and \#2 in one step: Using the appropriate numpy function, make a numpy array `L` of all integers from 0 - 19 (inclusive).

In [4]:
L = np.arange(20)

#### 4. Using "fancy indexing", replace all of the numbers in `L` that are divisible by 3 with -1.

In [5]:
# I actually intended for this to use a boolean mask, but I got confused on terminology.
# The boolean mask solution would be L[L%3==0] = -1. I suppose this solution is fine since even I did it wrong, 
# but maybe leave a comment.

# The fancy indexing solution would be this:
L[np.argwhere(L%3==0)]=-1
L

array([-1,  1,  2, -1,  4,  5, -1,  7,  8, -1, 10, 11, -1, 13, 14, -1, 16,
       17, -1, 19])

#### 5. Using numpy functions, compute the mean and standard deviation of `L`.

In [6]:
np.mean(L)
np.std(L)

6.848357467305573

#### 6. Using a numpy function, change `L` into a 5 by 4 matrix (5 row, 4 columns).

In [7]:
L = L.reshape((5,4))

#### 7. Using a numpy function (not a loop), compute the sum of all of the elements in `L`.

In [8]:
np.sum(L)

120

#### 8. Using a numpy function (not a loop) compute the mean of the elements in each column of `L`. Also compute the standard deviation of the elements in each row.

In [9]:
np.mean(L, axis=0)
np.std(L, axis=1)

array([1.29903811, 2.94745653, 4.74341649, 7.25861557, 8.01171018])

#### 9. Let's use numpy's random number generator. Seed it below with the number "2". (Note -- for the sake of reproducability, it's always a good idea to seed a random number generator.

In [10]:
np.random.seed(2)

#### 10. Using a numpy function, create two arrays each of 10 random integers between 1 and 3 (inclusive). Name these arrays `M` and `N`.

In [11]:
M = np.random.randint(1,4,10)
N = np.random.randint(1,4,10)
print(M,N)

[1 2 1 3 3 1 3 2 2 3] [1 1 1 2 3 1 3 3 3 2]


#### 11. Without using any loops, perform element-wise addition, subtraction, multiplication, and division of these two arrays. You do not need to store the results. (e.g. `[1, 2, 3]` + `[1, 2, 3]` = `[2, 4, 6]`)

In [12]:
M+N
M-N
M*N
M/N

array([1.        , 2.        , 1.        , 1.5       , 1.        ,
       1.        , 1.        , 0.66666667, 0.66666667, 1.5       ])

#### 12. Without using a loop, get all of the common elements between `M` and `N`. ("common" means they have the same value and position)

In [13]:
M[M==N]

array([1, 1, 3, 1, 3])

#### 13. Using a numpy function, get the positions where elements of `M` and `N` match.

In [14]:
# two options; argwhere is better in my opinion
np.argwhere(M==N)
np.where(M==N)

(array([0, 2, 4, 5, 6]),)

#### 14. Use the appropriate numpy functions to combine `M` and `N` into a 2 by 10 matrix and a 10 by 2 matrix. (Note -- the 10 by 2 matrix is more complicated. You will need to first turn `M` and `N` into column vectors.)

In [15]:
np.vstack((M, N))

np.hstack((M[:,np.newaxis], N[:,np.newaxis]))

array([[1, 1],
       [2, 1],
       [1, 1],
       [3, 2],
       [3, 3],
       [1, 1],
       [3, 3],
       [2, 3],
       [2, 3],
       [3, 2]])

## Section 2 -- "Dataframe" operations with `numpy`

### In this section, you will practice using `numpy` on the mtcars dataset that we've used previously in `R`. Here is a brief overview of this dataset, compliments of `R`:

A data frame with 32 observations on 11 (numeric) variables.

[:, 0]	mpg	Miles/(US) gallon

[:, 1]	cyl	Number of cylinders

[:, 2]	disp	Displacement (cu.in.)

[:, 3]	hp	Gross horsepower

[:, 4]	drat	Rear axle ratio

[:, 5]	wt	Weight (1000 lbs)

[:, 6]	qsec	1/4 mile time

[:, 7]	vs	Engine (0 = V-shaped, 1 = straight)

[:, 8]	am	Transmission (0 = automatic, 1 = manual)

[:, 9]	gear	Number of forward gears

[:, 10]	carb	Number of carburetors


#### We will mostly be dealing with only the first two columns. In the future, we will read in dataframes using `pandas`, which offers tools similar to what we've seen in `R`. For now though, I'm providing the lines for reading in using a `numpy` function not covered in the course material:

In [16]:
fname = "mtcars.csv"
mtcars = np.genfromtxt(fname, delimiter=',',skip_header=1)

#### 1. Examine this data set. What data type is each column (int, float, etc.)? Based on the description, what data type would you expect/hope for each column to be?

My wording is ambiguous, so maybe don't grade this one. They're loaded as floats. They're all actually mixes of floats, ints. You'd want that type to be preserved, but numpy doesn't do this easily.

#### 2. Use a numpy function to determine how many unique values there are in the ```cyl``` column.

In [17]:
len(np.unique(mtcars[:,1]))

3

#### 3. Extract all the rows with 6 cylinders. 

Note: Because these arrays are floating point-type, strictly speaking, using `==` can produce unexpected results. Using `numpy.isclose()` is the safer option. However, in this problem set, you can use `==`.

In [18]:
mtcars[np.argwhere(mtcars[:,1]==6),:]

array([[[ 21.   ,   6.   , 160.   , 110.   ,   3.9  ,   2.62 ,  16.46 ,
           0.   ,   1.   ,   4.   ,   4.   ]],

       [[ 21.   ,   6.   , 160.   , 110.   ,   3.9  ,   2.875,  17.02 ,
           0.   ,   1.   ,   4.   ,   4.   ]],

       [[ 21.4  ,   6.   , 258.   , 110.   ,   3.08 ,   3.215,  19.44 ,
           1.   ,   0.   ,   3.   ,   1.   ]],

       [[ 18.1  ,   6.   , 225.   , 105.   ,   2.76 ,   3.46 ,  20.22 ,
           1.   ,   0.   ,   3.   ,   1.   ]],

       [[ 19.2  ,   6.   , 167.6  , 123.   ,   3.92 ,   3.44 ,  18.3  ,
           1.   ,   0.   ,   4.   ,   4.   ]],

       [[ 17.8  ,   6.   , 167.6  , 123.   ,   3.92 ,   3.44 ,  18.9  ,
           1.   ,   0.   ,   4.   ,   4.   ]],

       [[ 19.7  ,   6.   , 145.   , 175.   ,   3.62 ,   2.77 ,  15.5  ,
           0.   ,   1.   ,   5.   ,   6.   ]]])

#### 4. Sort the rows of `mtcars` based on the `mpg` column. How many cylinders does the car with the lowest mpg have? What about the highest?

Note: Be careful not to only sort the values in one column. Rows need to be preserved because each row contains values for a specific automobile.

In [19]:
mtcars[np.argsort(mtcars[:,0]),:]

array([[ 10.4  ,   8.   , 460.   , 215.   ,   3.   ,   5.424,  17.82 ,
          0.   ,   0.   ,   3.   ,   4.   ],
       [ 10.4  ,   8.   , 472.   , 205.   ,   2.93 ,   5.25 ,  17.98 ,
          0.   ,   0.   ,   3.   ,   4.   ],
       [ 13.3  ,   8.   , 350.   , 245.   ,   3.73 ,   3.84 ,  15.41 ,
          0.   ,   0.   ,   3.   ,   4.   ],
       [ 14.3  ,   8.   , 360.   , 245.   ,   3.21 ,   3.57 ,  15.84 ,
          0.   ,   0.   ,   3.   ,   4.   ],
       [ 14.7  ,   8.   , 440.   , 230.   ,   3.23 ,   5.345,  17.42 ,
          0.   ,   0.   ,   3.   ,   4.   ],
       [ 15.   ,   8.   , 301.   , 335.   ,   3.54 ,   3.57 ,  14.6  ,
          0.   ,   1.   ,   5.   ,   8.   ],
       [ 15.2  ,   8.   , 275.8  , 180.   ,   3.07 ,   3.78 ,  18.   ,
          0.   ,   0.   ,   3.   ,   3.   ],
       [ 15.2  ,   8.   , 304.   , 150.   ,   3.15 ,   3.435,  17.3  ,
          0.   ,   0.   ,   3.   ,   2.   ],
       [ 15.5  ,   8.   , 318.   , 150.   ,   2.76 ,   3.52 ,  16.87 ,
 

#### 5. Create a new array called `mtcars_std` that standardizes all the columns of `mtcars` (mean of 0, standard deviation of 1).

In [20]:
mtcars_std = (mtcars-np.mean(mtcars,axis=0))/np.std(mtcars,axis=0)

#### 6. Create a new array called `mtcars_norm` which normalizes all the columns of `mtcars` (values between 0 and 1).

In [21]:
mtcars_norm = (mtcars-np.min(mtcars,axis=0))/(np.max(mtcars,axis=0)-np.min(mtcars,axis=0))

#### 7. Determine the mean `mpg` of cars with different numbers of cylinders (i.e., what is the average `mpg` for cars with 4, 6, and 8 cylinders?). 

In [22]:
ncyl_opt = np.unique(mtcars[:, 1])

for ncyl in ncyl_opt:
    ind = np.argwhere(mtcars[:,1]==ncyl)
    group = mtcars[ind, 0]
    print(ncyl, np.mean(group))

4.0 26.66363636363636
6.0 19.74285714285714
8.0 15.1


#### 8. Turn what you did in \#7 into a more general function: 
#### Write a function that performs a "group_by" on one column and returns the "group mean" of values in another column. You should pass to this function the array, the column you want to group by, and the column you want to calculate the mean of.
#### Have the function return a list of (group, mean) tuples that look like this `L = [(group1, mean1), (group2, mean2), ...]`.
#### Test this function by computing the mean `mpg` for cars with different numbers of cylinders. This test should return something like `[(4.0, 26.7), (6.0, 19.7), (8.0, 15.1)]` (Note that I rounded these)

In [23]:
def group_mean(mtcars, col, by):
    unique_vals = np.unique(mtcars[:, by])
    unique_vals
    
    L = []
    
    for val in unique_vals:
        tmp = mtcars[np.argwhere(mtcars[:,by]==val), col]
        mu = np.mean(tmp)
        L.append((val,mu))
    
    return(L)

group_mean(mtcars, 0, 1)

[(4.0, 26.66363636363636), (6.0, 19.74285714285714), (8.0, 15.1)]

## Section 3 -- Matrix Multiplication

#### A common programming problem involves writing a function to perform a matrix multiplication. Please review the procedure for multiplying two matrices if you have forgotten. In this section you'll perform matrix multiplications using the following matrices:

In [24]:
np.random.seed(0)
M = np.random.randint(1,6,(3,3))
N = np.random.randint(1,6,(3,3))
L = np.random.randint(1,6,(3,4))
print("M:\n{}\n\nN:\n{}\n\nL:\n{}".format(M, N, L))

M:
[[5 1 4]
 [4 4 2]
 [4 3 5]]

N:
[[1 1 5]
 [3 2 1]
 [2 2 1]]

L:
[[2 5 4 1]
 [4 1 3 4]
 [1 2 4 4]]


#### 1. Write a function called "matrix_multiply" that takes in two matrices and returns their matrix product. 
#### Test that the function works for `M` x `N` and `N` x `L`. For `L` x `M`, raise an appropriate error message to indicate the issue.
#### For this part, do not use any built-in numpy functions designed for matrix multiplication.
#### (Note: don't worry if your function changes the integers to floats. You can fix this if you like!)

In [25]:
## function here

def matrix_multiply(M, N):
    if M.shape[1]!=N.shape[0]:
        raise ValueError("Matrices are not compatible for multiplication")
    
    L = np.zeros((M.shape[0], N.shape[1]))
    
    for irow in range(L.shape[0]):
        for icol in range(L.shape[1]):
            L[irow,icol] = np.sum(M[irow,:]*N[:,icol])
    
    return L

In [26]:
## tests here
# matrix_multiply(L, N)
print(matrix_multiply(M,N))
matrix_multiply(N, L)

[[16. 15. 30.]
 [20. 16. 26.]
 [23. 20. 28.]]


array([[11., 16., 27., 25.],
       [15., 19., 22., 15.],
       [13., 14., 18., 14.]])

#### 2. What function(s) already exist in numpy for performing matrix multiplication? Using one or more of these functions, check that your function is performing correctly. What type of error is raised when you try to multiply `L` by `N`?

In [27]:
# Three different options
M.dot(N)
np.matmul(M,N)
M@N

# All of these raise a ValueError with an appropriate message
# L.dot(N)
# np.matmul(L,N)
# L@N

array([[16, 15, 30],
       [20, 16, 26],
       [23, 20, 28]])

#### 3. How does the timing of your code compare to that of numpy's built in function(s)? Test using both `M`x`N` and the larger matrices, `M1` and `M2`, defined below.

In [28]:
M1 = np.random.randint(1,6,(200,300))
M2 = np.random.randint(1,6,(300,500))

In [29]:
%time matrix_multiply(M1,M2)
%time M1.dot(M2)
%time np.matmul(M1,M2)

CPU times: user 968 ms, sys: 8.47 ms, total: 977 ms
Wall time: 1.01 s
CPU times: user 21.9 ms, sys: 153 µs, total: 22.1 ms
Wall time: 22 ms
CPU times: user 33.6 ms, sys: 346 µs, total: 33.9 ms
Wall time: 35.4 ms


array([[2618, 2604, 2682, ..., 2710, 2782, 2720],
       [2685, 2580, 2716, ..., 2754, 2770, 2758],
       [2693, 2668, 2711, ..., 2725, 2701, 2734],
       ...,
       [2705, 2649, 2751, ..., 2790, 2750, 2739],
       [2728, 2708, 2814, ..., 2789, 2857, 2809],
       [2598, 2577, 2697, ..., 2695, 2771, 2704]])

#### 4. Your function is likely slower than the numpy function. Use the appropriate "magic command" below to inspect which part(s) of your function are the slowest. Why are these parts slow compared to the  `numpy` functions?

In [30]:
%load_ext line_profiler
%lprun -f matrix_multiply matrix_multiply(M1,M2)

The slowest part by far is the inner piece of the for loop, where I perform the algebra. I am here technically still using two numpy functions (the multiply ufunc and sum), but not ones designed for matrix multiplication. Because of this, my implementation is faster than those that might add in a third loop, but I didn't do the comparison.

Python is interpreted line-by-line. Each time I execute that inner piece of the for loop, Python has to examine the data type of the arrays and look-up/dispatch the appropriate function for that data type. This process is repeated (in this case) 100,000 times. It would be even more than that if I had not used numpy in the inner loop. Performing this lookup more than once is unnecessary, because the types never change. The numpy functions for matrix multiplication are executed on compiled code, which results in less flexibility but also less overhead, making them faster.